import Navbar from "../components/Navbar";
import "./globals.css";
import { AppContextProvider } from "@/contexts/AppContext";

export const metadata = {
  title: "Ecoyaan",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AppContextProvider>
          <Navbar />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
